{% set name = "astromodels" %}
{% set version = "2.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/astromodels-{{ version }}.tar.gz
  sha256: d2ec683d7fb625e9c230a22d5125f54b5771604df8535661f47b6efdc14430bf

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - numpy
    - pip
    - python
  run:
    - astropy >=1.2
    - colorama
    - dill
    - future
    - h5py
    - interpolation
    - numba
    - numpy >=1.6
    - omegaconf
    - pandas
    - python
    - rich
    - pyyaml >=5.1
    - scipy >=0.14
    - pytables
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - astromodels
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/threeml/astromodels
  summary: Astromodels contains models to be used in likelihood or Bayesian analysis in astronomy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
