{% set name = "astromodels" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/astromodels-{{ version }}.tar.gz
  sha256: cdf305d32ecad028842b99a940076972a112674fc6252a312f9e9521d81cc8a5
  patches:
    - versioneer.patch

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [win]
  skip: true  # [py==38]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - numpy
    - pip
  run:
    - python
    - numpy >=1.6
    - pyyaml >=5.1
    - scipy >=0.14
    - astropy >=1.2
    - dill
    - future
    - interpolation >=2.2.6
    - numba >=0.57
    - h5py
    - pandas
    - pytables
    - colorama
    - omegaconf
    - rich
    - joblib

test:
  imports:
    - astromodels
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/threeml/astromodels
  summary: Astromodels contains models to be used in likelihood or Bayesian analysis in astronomy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
